spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  messages:
    basename: i18n/locale
    encoding: utf-8
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/portal?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080

