spring:
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
  messages:
    basename: i18n/locale
    encoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/portal?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
server:
  port: 8080
