DROP TABLE IF EXISTS "user";

CREATE TABLE "user"
(
    id    VARCHAR(32)   NOT NULL,
    name  VARCHAR(30) NULL DEFAULT NULL,
    age   INT         NULL DEFAULT NULL,
    email VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (id)
);